usgs-makerspace/wbeep-viz

src/components/MapBox.vue
Dynamic Sizing of Map div
-----------
Change height of #map div to accommodate different viewports.
Description
-----------
The original configuration of the #map div used a fixed height of 900px.  This caused the map
canvas to extend beyond the viewport on most clients, requiring the user to scroll to see the full map.  This change styles the #map div with a relative size of 60vh, which renders the map responsively regardless of the client or viewport size.
=> Wbeep 89 dynamic sizing of map on load

CHANGELOG.md, src/assets/mapStyles/mapStyles.js, src/components/MapBox.vue
- Added a little opacity to the HRU's
- Removed the City Dots
- Removed the HRU outlines
- Removed the styling to the city names so they will sit where the dots used to be and not floating over a non existent dot.
- Adding zoom to bounding box, which is nice for mobile and larger screens!
- Adjusted minimal zoom, as the bounding box zoom can't adjust to phone screen sizes with a minimum zoom of 3.  Downgrade the HRU's disappear as they don't have tiles at zoom level 2.
=> Removed City dots and HRU Outlines, added bounding box zoom

jenkins/Jenkinsfile.build
Add Jenkins Exclude for 'openmaptiles' folder on s3
-----------
Need to put our new tiles on S3 for hosting and don't want the Jenkins job to delete them on every build, so I added an exclude statement to the Jenkins file.
=> added jenkins exclude for openmaptiles

src/assets/mapStyles/mapStyles.js, src/components/MapLegend.vue
Separating Logic from Styles
-----------
This is an add on to Marty's addition of the modal to the legend. In effort to keep it so that common changes to the Mapbox gl style sheet will simply be processed by the application rather than breaking it, I tweaked the code a bit. 
In the process of testing this, I noticed the new modals look great on the desktop, but will require a bit of adjustment on mobile devices.  
P.S. I have been running 'npm run lint --fix' before doing a pull request. That is where all the odd formatting changes are coming from. Seems like the makers of Vue like everything on multiple lines.
=> Separate styles and logic

src/components/MapBox.vue
Add Zoom Indicator
-----------
Added a indicator below the map and above the footer so that we can see the current zoom level while we are styling the map. This is intended for development and will not remain in the final version. 
=> Add zoom indicator

CHANGELOG.md, src/components/MapBox.vue
Toggle Icons stay on the right of the screen at all times now.
ToggleOptions are evenly divided space wise now when they show up.  Currently when its one option it is pretty huge, but we could do some adjusting if we don't like that.
=> toggle nav changes

src/components/MapBox.vue
Comment out the Zoom Level
-----------
A small change to comment out the zoom level display. We only use this for development and don't want it on the production level of the application. 
Eventually it would be good to make this a build tier dependent feature toggle. 
=> Comment out zoom level

src/components/footerEmail.vue
Pretty small, bbut actually have a mailto: href *eyeroll and the email address finds a new line on smaller screens to avoid it awkwardly breaking like gs-
w_onhm@usgs.gov <--new line, bleh
=> Footer Email Change

jenkins/Jenkinsfile.build
Removed Unneeded Excludes
-----------
Since the our independent tile server is up and running, I switched over to using it rather than the files on WBEEP 'test' then deleted those files. This should allow the build tile to return to the original under three minute time.
Also, we could move 'basetiles' as well.  
=> removed excludes that are no longer needed

config.sh, src/assets/mapStyles/mapStyles.js
Change Tile Cache
-----------
Okay, since the hard coded addition of '?fresh=true' to the call to get the hydro logical response unit source code, I am going to go ahead and change the build to accept the change.
=> change config to use ?fresh=true

CHANGELOG.md, src/components/About.vue, src/components/FooterUSGS.vue, src/components/MapBox.vue, src/components/MapLayers.vue, src/components/MapLegend.vue, src/components/MapSubtitle.vue
Add Google Analytics Event Tracking
-----------
Added Google Analytics Event Tracking for most user click events.
Description
-----------
Adding Google Analytics (GA) Event Tracking was an easy task for most items that users can interact with using a click. This was accomplished using a '@click' Vue binding and feeding in the desired GA parameters. The challenge came with getting GA to attach to links that were dynamically created such as those in the 'layers menu' and the legend. That required some sort of passing of the GA global variable (this.$ga) into the scope of the function created the clickable items. I did get this to work, but I am not sure that what I came up with is the best possible method. 
Also, I could not find an …
=> Add event tracking for google analytics

CHANGELOG.md, src/assets/mapStyles/mapStyles.js
Description
-----------
So was able to combine the roads into one layer call just using their already in place fancy filter, just combined the classes together instead of making separate layers.  The functionality seems untouched, the smaller roads still only show up as you zoom in and line width still seems defined.  It feels too easy, but until I'm proven otherwise I'm running with a simple solution.
=> Roads toggle

CHANGELOG.md, src/assets/mapStyles/mapStyles.js
Description
-----------
While playing around with our paint options for the HRU's, I noticed the white slivers stopped being made when I removed the fill-outline-color from the paint property.  The slivers still do show up when zooming in, but are rendered out when mapbox-gl is done rendering the tiles.  
Maybe we just have too many polygons to be using the fill-outline-color?  I couldn't tell you for sure, but it does seem to be the culprit.  We will see what the future brings.
=> white slivers removal?

CHANGELOG.md, src/assets/mapStyles/mapStyles.js
Title
-----------
Change river layer styles to match openmaptiles tiles for rivers/waterbodies
Description
-----------
Used the RGB from the openmaptiles waterbodies/rivers 
https://github.com/usgs-makerspace/makerspace-sandbox/issues/212
=> Change river layer styles to match openmaptiles tiles for rivers/waterbodies

src/assets/mapStyles/mapStyles.js, src/components/About.vue, src/components/HeaderUSWDSBanner.vue, src/components/MapBox.vue, vue.config.js
Put Min Zoom on Stream Orders
-----------
Made it so the stream orders will only show on zoom levels of 8-24. 
There were some Tippecanoe compression artifacts for stream orders on zoom levels above 8. We want to hide these from the end user, so I set the zoom level appropriately. 
We will be working more on the streams in temperature prediction part of the WBEEP project, so we will revisit this at a later time. 
P.S. Only the first page of changes are of interest in the review. All the other changes were the result of running 'npm run lint --fix'
=> Make stream orders visable past zoom 8

.env.production
Change to Use CloudFront URL for Production
-----------
Since the public tiers of the application use HTTPS created through CloudFront the browser wants all the resources to also be secure as well, so I switched the hydrologic response unit tile source to use the CloudFront URL of the 'prod' bucket.
=> change to use cloudfront url for hrus

src/components/LoadingScreen.vue
Description
-----------
Testing on mobile has proven the loading screen to be a bit buggy (nothings ever easy).  One bug being a user can scroll the loading screen and see the map before the loading is complete.  This prevent touchmove on the loading div prevents that and is a less buggy looking mobile experience. 
=> Prevent Scrolling

.env.production, src/assets/mapStyles/mapStyles.js
Change Model date and NHD Stream Orders to Use Secure Resources
-----------
I switched the call to retrieve the model date to use the CloudFront URL of the 'prod' bucket, and I added an 's' to the 'http' so that it would make an encrypted request to the 'maptiles-prod' tile server bucket.
=> changed to secure resources for date and rivers

package-lock.json, package.json, src/main.js
Fix to Get Internet Explorer 11 Running
-----------
So these changes represent about 20 hours of developer time. Basically there were four intertwining issues that made this perplexing. 1) The need for a polyfill for the ES6 Promises that are used by the Google Analytics plugin. This caused IE 11 to fail and was solved by importing es6-promise polyfill. 2) The newest version of 'vue-svg-loader' has an issue which causes both Edge and IE11 to fail, in the end I was forced to downgrade the version from 0.12.0 to 0.10.0. 3) A similar issue existed for 'core.js' in its latest version, and I was forced to downgrade it to 3.3.2. 4) The 'vue-mapbox' plugin requires a specific trans-piling command in the 'vue.config.js' file so that the …
=> Fix for edge

.env.beta, .env.qa
Change Tile URL to Match Bucket
-----------
Since we are now deploying the Hydrologic Response Unit tiles to directories on each tier, we can change the URL to pull the tiles directly from the tier.
=> changed tile url to match bucket

CHANGELOG.md, src/components/MapBox.vue
Description
-----------
Found that the USWDS banner seems something to do with the map whitespace on the initial load.  A quick and easy solution is running map.resize() during the map creation.  Maybe doesn't solve the entire mystery, but gets us a better looking product.
Also in my search I found some of my CSS was unnecessary, so less code is always better.
=> mapresize solution

package-lock.json, package.json
First . . .
Finally . . .
Add Vue-Router as a Project Dependency
-----------
So . . . somehow, Vue-Router was left out of the project and thus the Jenkins' build failed . . . yet the project still ran on my local machine?!
Not really sure how that happens, but I am thinking this will fix it.
=> adding vue router dependency

build.sh
First . . .
Finally . . .
Changing the Build Script Names
-----------
I decided not to change the Jenkins job runner drop down menu names, but I forgot that the build script actually matches those and not the 'real' build mode options. So I am changing them back.
=> changed names in build back to match jenkins drop down

package-lock.json, package.json, src/components/MapBox.vue, vue.config.js
First . . .
Finally . . .
Add Explicit NODE_ENV Setting to Package.json Scripts
-----------
Set the NODE_ENV environment variable explicitly 
Description
-----------
Okay, so, yeah. We were seeing a HUGE JavaScript bundle size which was really bogging down the loading of the application. To figure out why, I installed a Webpack plugin called Webpack Bundle Analyzer. This showed that we were having a problem with Font Awesome, and even though we were importing each Font Awesome icon individually, the ENTIRE Font Awesome library was being imported into the final JavaScript bundle making it about four megabytes, ouch.
I dug into this, and …
=> Shrink bundle

package.json, vue.config.js
First . . .
Finally . . .
Remove Bundle Analyzer Plugin
-----------
I had a feeling this would hang the Jenkins build, and it did.  It is pretty simple to install the plugin when needed, which might be for the best since the way it creates a new browser window at the end of each build (which is what hung Jenkins), could prove annoying at times when you don't care about the JavaScript bundle composition. 
=> removed the bundle analyzer plugin

src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Flexbox was being too cute with how it was sizing the tabs on browsers, so had to write stricter CSS to prevent the odd looking unaligned line from happening.  Don't like being the strict parent, but gotta be done sometimes.
=> Legend tabs alignment on all browsers

CHANGELOG.md, src/App.vue, src/components/MapBox.vue, src/components/MapSubtitle.vue, src/components/ProvisionalStatement.vue, src/components/SubtitleModal.vue, src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Required Changes to Show Provisional Status
-----------
Added a provisional statement at the bottom and set the 'about this map' informational box to be open when the page is loaded. I also set an event that will close the informational box if a click event happens anywhere in the map area. This only happens once, and the page resumes normal functionality -- until someone goes to the 'questions page' then the process starts over, because the page reloads. 
=> Wbeep 310 infobox always on

.env.beta_tier, .env.prod_tier, .env.qa_tier, .env.test_tier, jenkins/Jenkinsfile.build
First . . .
Finally . . .
Change Prod and Beta to Use the User Friendly URLs
-----------
Changed the file paths so that the 'prod' and 'beta' tier will now make tile and date requests using the user friendly URLs.
Description
-----------
Since there was some suggestions made that the weird CloudFront URLs were 'internal' and that we should not show 'internal' URLs to the world, I switched them to use the 'user friendly URLs'. Of course is not a straight forward thing, since in order to use the 'user friendly URLs' we have to move the date and tiles from the 'root' of the bucket to a nested folder in much the same way we had to move the …
=> changed to have tiles n date files in nested folder

src/components/ProvisionalStatement.vue
First . . .
Finally . . .
Description
-----------
Made the condensed statement a span and added the button to it to avoid trying to fight aligning the button and text separately.  
The float that was making the button and text next to each other was acting funky on mobile.  It looked like it had disappeared, but in the end the float was just acting like there was no content and was smooshing the hell out of the div.  I did a quick flexbox fix and everything seems to be working again.
=> Provisional statement on mobile

CHANGELOG.md, src/App.vue, src/components/FooterUSGS.vue, src/components/MapBox.vue, src/components/MapLayers.vue, src/components/MapLegend.vue, src/components/ProvisionalStatement.vue, src/components/QuestionControl.vue, src/main.js
First . . .
Finally . . .
Add Google Analytics Custom Dimension for ClientId
-----------
Added a Google Analytics custom dimension to the dashboard and then extracted the value from the Google Analytics cookie to populate the custom dimension. According to Google, this is not best practice (as they may change the cookie in the future and our code will break), but there does not seem to be a better way to do it right now, and I added a catch that should grab any errors caused by the cookie not having thing where we expect them to be. So at least the application should keep running, minus the ClientId for the analytics.
After making a …
=> Add google dimension client

src/main.js
First . . .
Finally . . .
Minor Change to Add ClientId to the Initial Vue Analytics Load
-----------
This change just sets the 'timestamp' so that it will be there when the page first loads. Any click events after the first load will reset the timestamp.
=> added timestamp to the initial vue analytics load

CHANGELOG.md, src/components/MapAvailableDataDate.vue, src/components/MapBox.vue, src/components/MapSubtitle.vue, src/components/SubtitleModal.vue
First . . .
Finally . . .
Description
-----------
Subtitle was improperly formatting itself when faced with a lack of space.  Some adjustments to how the CSS is formed has fixed this.  
Other changes is the min-height to the map container, as I saw old iphones could never get the full map on their tiny phones at once. Also bolded the date in the subtitle date module.  Seems more important now, but can always be reverted.  finally added a white-space: pre on the date, so it never shifts dumbly like 12-
09-19
^ Cause thats dumb looking 
=> Subtitle mobile fix

CHANGELOG.md, src/components/MapBox.vue, src/components/MapSubtitle.vue
First . . .
Finally . . .
Fix Bug Requiring Double Click to Close Map Info Box
-----------
When the user clicked on the map info close box, it triggered both the close box click and the click 'anywhere' click, which basically closed then reopened the info box before the user could see a change, making appear as if it did not close. I added some conditional logic that to stop the second click event from toggling the box on the first event.   So, all should be okay now.
=> Fix double click

CHANGELOG.md, src/components/MapBox.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Was able to use a pretty cool bounding box tool to find a bounding box that allows us to zoom out enough for mobile and fitbounds, but doesn't allow the user to pan all over the globe.
=> Map Bounding Box Tweak for Mobile

CHANGELOG.md, src/components/MapBox.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
We discovered its actually the openmaptiles disappearing not the BG layer.  I was under the impression the BG layer was blue, but it is currently cream.  So for now stopping the zoom from going in the last .01 zoom that the openmaptiles disappear.
=> Blue background fix

CHANGELOG.md, src/assets/mapStyles/mapStyles.js
First . . .
Finally . . .
- [x ] Update the changelog appropriately
Change Zoom to Allow Counties to show
-----------
Fixed the issue that prevented the county lines from showing when the user toggles them
Description
-----------
Allowed counties to show at zoom level 4 and higher. 
Changed the county lines to give them less visual weight and make them appear more distinct from the state lines
=> changed the appearance and zoom levels for counties

CHANGELOG.md, src/assets/mapStyles/mapStyles.js, src/components/MapBox.vue
First . . .
Finally . . .
Zoom Level Sensitive Layer Menu Buttons
-----------
This uses our 'zoom level' indicator knowledge to make the Menu Layer buttons active only when they layers are available for viewing, as set in the mapStyles file.
Sorry about all the changes to the quote marks. I'm trying to consolidated to the use of single quotes in the code and double quotes in the Vue template (as required by the Vue Linter), but those changes make it hard to see the important alterations. Anyway, I think this is are big user enhancement, but who knows what the rest of the world will think. Also, BrowserStack is not working for me at the …
=> Exp activate button only on some zoom level

src/assets/mapStyles/waterTemperature/mapStyles.js, src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Example of Mapbox Expressions
-----------
This uses Mapbox expressions to generate an 'infinite' range of colors based on the value of the data. This is not intended to be the final version of this issue but more of an example of both Mapbox expressions to make the color range and the a continuous color ramp.
=> contiuous color ramp using mapbox expressions

jenkins/Jenkinsfile.build
Ivan reviewed our problematic re-running pipeline and tested with a clone of the job and it seems like that job isn't re-triggering repeatedly, here are the changes: 
- add polling trigger to jenkinsfile
- use parameters default selectedValue and origin/master for defaultValue
- add .git to the repo path
First . . .
Finally . . .
Title
-----------
Description
-----------
=> Jenkinsfile updates - from JIRA CTEK-103

src/views/waterStorage/WaterStorage.vue
First . . .
Finally . . .
Fix - this keeps the old header on all the tiers except 'test
-----------
When changing the header, I forgot that we wanted to keep the old WBEEP-Water-Storage available for updating but still hide the new features from users. This change keeps that capability.
=> added change to keep current header on all but test tier

CHANGELOG.md, src/components/waterUse/RadialChart.vue, src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Add the d3 radial chart placeholder into water-use view
-----------
Added a d3 solution for the radial charts to the water-use view above the map. Still working on mock-ups for what the radial charts look like in the end, but at least there is some code to start with. Also, added the button back in that got deleted in https://github.com/usgs-makerspace/wbeep-viz/pull/381. This work addresses https://github.com/usgs-makerspace/makerspace-sandbox/issues/475.
=> Add an example d3 radial chart

.env.beta_tier, .env.prod_tier, package-lock.json, package.json
First . . .
Finally . . .
Change Target URLs to use CloudFront
-----------
This is a small change in preparation for the for the addition of the Stream Temperature feature.
The target URLs for the Stream Temperature tiles should be correct now. The tiles are not yet at those locations, but when the arrive, we will be ready.
=> Change urls to use cloudfront for temp

src/components/ApplicationFeatureSelection.vue, src/components/LoadingScreenInternal.vue, src/views/waterStorage/WaterStorage.vue, src/views/waterTemperature/WaterTemperature.vue, src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/571
only show the partial splash screen on pages where the nav bar shows. accommodate QA build to make sure it works on both deployments 
Description
-----------
modified the css in the ApplicationFeatureSelection vue file so that when this component is active (regardless of tier) it adjusts the splash screen to accommodate the nav bar
in turn, when that is not present, modifed the css in each of the page vue files to do the same. it will work both on tiers that are told to show the nav bar as well as those who do not with these …
=> make loading screen changes work on both test and qa builds

src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
change the line width on streams_interpolated layer so that they adjust with zoom level
Description
-----------
added an expression so that as the user zooms the line thickness on the rivers get wider
=> use interpolation between zoom levels to determine line thickness

src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
only allow zoom levels to 6
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/603
=> limit zoom level for stream layers to 6

src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Keep entire map zoom just below max zoom of tile layer
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/603
=> adjust so that map zoom level is slightly below tile max

src/components/LoadingScreenInternal.vue, src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
I can't seem to figure out how to explicitly wait for the Map SVG to render to make the loading screen go away, but heres another attempt.  Always works locally, but never on test.
=> Another attempt to having loading screen wait for map svg

vue.config.js
First . . .
Finally . . .
Title
-----------
Description
-----------
I previously had to disable the SVGO convertTransform control to have the barchart to display properly, but now that doesn't seem to be the case.  With it enable the SVG load has gone from 2.6MB to 25.4KB.  Pretty big difference.
=> SVGO transform control

src/assets/wuBarSVGs/svg_bars_ir.svg, src/assets/wuBarSVGs/svg_bars_ps.svg, src/assets/wuBarSVGs/svg_bars_te.svg, wu_pipeline/6_visualize/src/build_svg_bars.R
We may need to do more beyond this, but my first thought was to move the x-axis down. It was overlapping the data due to having a stroke-width of 5, so I just needed to shift it down 2.5 so that the width brought it right up to the bottom of the data. You can now see the slivers of data. Once it is on test, we may want to talk about additional tricks to get those bottom slivers to be even more visible.
Part of https://github.com/usgs-makerspace/makerspace-sandbox/issues/652
=> Make irrigation winter visible

src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
hide canada's river segments
Description
-----------
re-ordering the different tile sets
=> re-order layers so that we block the river segments in canada

src/assets/wuMapSVGs/svg_map_ir_fall.svg, src/assets/wuMapSVGs/svg_map_ir_spring.svg, src/assets/wuMapSVGs/svg_map_ir_summer.svg, src/assets/wuMapSVGs/svg_map_ir_winter.svg, src/assets/wuMapSVGs/svg_map_ps_fall.svg, src/assets/wuMapSVGs/svg_map_ps_spring.svg, src/assets/wuMapSVGs/svg_map_ps_summer.svg, src/assets/wuMapSVGs/svg_map_ps_winter.svg, src/assets/wuMapSVGs/svg_map_te_fall.svg, src/assets/wuMapSVGs/svg_map_te_spring.svg, src/assets/wuMapSVGs/svg_map_te_summer.svg, src/assets/wuMapSVGs/svg_map_te_winter.svg, wu_pipeline/6_visualize/src/build_svg_map.R
Updates legend title (via https://github.com/usgs-makerspace/makerspace-sandbox/issues/668) and moves units onto second line. Added extra class to `tspan` that contains the units only so that they can be styled differently (smaller, italicized, etc) if @mwernimont thinks they should be.
=> Update legend title

wu_pipeline/README.md
How to run the viz pipeline to build or rebuild the water use SVGs. You will actually need access to the ScienceBase items that are needed, so we should request that Rich give us all access to all of those items. I think @mhines-usgs  you are just missing the [recent centroid geojson](https://www.sciencebase.gov/catalog/item/5f7fc9a682cebef40f0f1c3b).
=> add README for water use viz pipeline

src/components/References.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/689
Description
-----------
move references around to match the order of water storage, water use, water temperature
=> move water use refs above water temp references

src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Separated the map from the other contents constraints and gave it an arbitrary 1500px max-width.  Feel free to play with the max-width CSS declaration in the Water Use CSS on #waterUseMapContainer and see if you like another max-size for your screen.
=> WBEEP #674: water use: make the map bigger on desktop/laptop view

Dockerfile
First . . .
Finally . . .
Title
-----------
workaround for docker hub rate limit failure
Description
-----------
per an email from ivan, we should try to have our own artifactory mirror the package if we can. we just bumped into this a little while ago building the wbeep-viz ui on jenkins, hopefully this fixes.
=> use artifactory mirror to get around docker hub limit

src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/680
Description
-----------
- removed the baselayer water features because we wanted to eliminate inland water bodies that are making it hard to interpret the stream temp colors
- created a new tile set for only the great lakes and added to a jenkins job that puts the tiles in our s3 maptiles prod bucket (pr to come for wbeep-processing jenkinsfile behind that)
- re-ordered the layers to get arrangement correct
- adjusted the oceans and great lakes water color to be the more 'bold' blue color from water storage that people liked in …
=> Layer adjustments related to inland waters

src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
move counties on top of the state fill layer
Description
-----------
goofed up layer order for counties, needs to be on top of state fill.
=> move counties on top of the state fill layer

src/views/waterStorage/WaterStorage.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
So I got it to highlight blue correctly, but VPN is not letting me log on to see if the roads layers loads correctly too, but I am guessing it would?
Anyways, the issue seems to have been how we wanted this layer active AND unavailable at the beginning height.  The function that got rid of the unavailable class was doing a hard class clear, so active was wiped as well.  So, I switched it to classList functionality, that way we can specifically change the unavailable class over doing hard wipes.  Let …
=> Layers Road Bug Fix

package.json
The dependabot version had a conflict I wasn't sure how to resolve, and since the dependabot service changed so it will no longer resolve its own conflicts, just re-did the PR here
First . . .
Finally . . .
Title
-----------
Description
-----------
=> uswds from 2.7.1 to 2.12.0

package.json
The dependabot version had a conflict I wasn't sure how to resolve, and since the dependabot service changed so it will no longer resolve its own conflicts, just re-did the PR here
~~
First . . .
Finally . . .
Title
-----------
Description
-----------
=> update fontawesome-svg-core from 1.2.29 to 1.2.35
