- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
added a changelog and pull request template
> added pull request template and blank changelog

- src/components/MapBox.vue
Title
-----------
Description
-----------
> WIP Display hru by category

- CHANGELOG.md
- public/index.html
- src/App.vue
- src/components/HeaderUSWDSSelections.vue
- src/components/MapBox.vue
Fix Title Bar
-----------
This fixes a small error in the title of the menu bar and changes the page title to WBEEP-Prototype  
Description
-----------
Minor bug fix
> Fix title bar

- CHANGELOG.md
- src/components/MapBox.vue
Title
-----------
Description
-----------
Took Megans awesome data and made a basic basemap.  River pop in at zoom level 5, counties at zoom level 6.  All very customizable in the style variable.  
> Basic Basemap to have for meantime

- CHANGELOG.md
- src/App.vue
- src/components/HeaderUSWDSSelections.vue
- src/components/MapBox.vue
Fix Wide Titles
-----------
Made some style changes to titles
Description
-----------
When working on another ticket, I noticed that titles I had done earlier looked like stank when the page was wide. So I added a bit of styling to make them a touch more palatable. 
> Fix wide titles

- CHANGELOG.md
Deleted Second 'mbtiles' Folder
-----------
Removed an unused folder
Description
-----------
I added a folder containing generic tiles for local work and it is not needed, so I am deleting it to prevent confusion
> deleted second mbtiles folder

- CHANGELOG.md
- src/components/MapBox.vue
Added Simple Map Controls 
-----------
Used the power of Mapbox-gl to add fullscreen toggle, increase/decrease zoom, and jump to location buttons
> added map controls

- package-lock.json
- package.json
Updated Dependencies
-----------
General dependency update
Description
-----------
I received a Github notification that some dependencies were out of date. Hopefully, this will take care of that. I tested it locally and everything still seemed to work. If anyone notices a change let me know. Remember to restart your Vue development server after pulling the changes.
> npm update of dependencies

- CHANGELOG.md
- src/components/HeaderUSWDSSelections.vue
- src/components/MapBox.vue
Change Layer Order
-----------
Adjusted the layers so political boundaries were easier to see.
Description
-----------
Changed the order of the layers and tweaked the opacity and borders of the HRU layer. Gave a poll on Slack and the majority were in favor - can always make additional changes later.
> Change layer order

- CHANGELOG.md
- src/components/MapBox.vue
Title
-----------
New cities base map layer
Description
-----------
- Updated basemap creation to create source layers, that we we don't call all the layers for every layer and filtering to the one we want.  We only call what we want now.
- Dotted state lines to show its possible
- Cities added to basemap
> New cities base map layer

- package-lock.json
- package.json
- src/components/HeaderUSGS.vue
- src/components/HeaderUSWDSBanner.vue
- src/components/HeaderUSWDSSelections.vue
- src/components/MapBox.vue
Updated Dependencies Part 1
-----------
General dependency update
Description
-----------
Update of mabox-gl and Vue-service. The update to Vue-service seemed to trigger a bunch of linting errors. 
I ran the linting auto fix to clear them.
> updated vue and fixed related linting errors

- babel.config.js
- package-lock.json
- package.json
Update Dependencies Part 2
-----------
Updates 'core-js' to 3.1.4
Description
-----------
The change from 'core-js' 2.6.5 to 3.1.4 was a breaking change that caused 'babel' to look for files that
no longer exist in the new version of 'core-js'. After much internet searching I was able to find a sample of code that modified the 'babel.config.js' telling 'babel' not to look in the 'core-js' folder. Here is the explanation:
'This option adds direct references to the core-js module as bare imports. Thus core-js will be resolved relative to the file itself and needs to be accessible. You may need to specify core-js@2 as a top level dependency in your application if there isn't a core-js dependency or there are multiple versions.'
After …
> Update dependencies 7 19 19 part 2

- package-lock.json
- package.json
- src/components/MapBox.vue
General Dependency Update 8_12_19
-----------
General update of dependencies
Description
-----------
For some reason, I was unable to update the dependencies through the normal path of changing the version numbers in the 'package.json' so is used Node Package Manage to do a bulk update which seemed to work. 
Tested locally, the map appeared as expected.
This also includes some minor formatting changes created by using 'npm run lint --fix'
Note if you hit the error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY . It is NOT a result of these changes an can be fixed by running this command: npm config set registry http://registry.npmjs.org/
> Update dependencies 8 12 19

- LICENSE.md
- package.json
- src/assets/mapStyles/mapStyles.js
Dependency Update 8 28 19
-----------
This is a general dependency update. I also added the USGS license to the repository
> Update 8 28 19 and liscense

- CHANGELOG.md
- jenkins/Jenkinsfile.build
Title
-----------
Parameterized git branch/tag in Jenkinsfile
Description
-----------
Fixes https://github.com/usgs-makerspace/makerspace-sandbox/issues/143
- [x ] If appropriate, put the link to the PR in the ticket
- [ x] Assign someone to review unless the change is trivial
> parameterize git tag/branch

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Added Mapbox Layers for Testing
-----------
To move the styling process forward, I added set of Mapbox layers for people to test.
> Mapbox test

- CHANGELOG.md
- src/App.vue
- src/components/FooterUSGS.vue
- src/components/HeaderUSWDSBanner.vue
- src/components/MapBox.vue
- src/components/MapLegend.vue
Used Flexbox, a css magic machine https://css-tricks.com/snippets/css/a-guide-to-flexbox/ to create a more fluid layout for the map and the rest of the content.
> Flexbox CSS Magic for layout fluidity

- CHANGELOG.md
- jenkins/Jenkinsfile.build
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
- src/components/MapLegend.vue
Test of The OpenMapTiles Streets layer
-----------
Added the OpenMapTiles layer for streets (and much more)
Description
-----------
I removed the Mapbox layer for streets and replaced it with a OpenMapTiles version. The OpenMapTiles are a set of vector tile layers that have state boundaries and city names and much much more. I left our original base layers for streams, neighboring countries, and county borders, these are now marked with an asterix '*' before their name on the layer toggle bar.
The OpenMapTiles are now on 'test' and I have hard coded the URL. This seems to test fine on Chrome, but locally I am getting CORs related error in Firefox.  I uploaded the OpenMapTiles (after many hours due to poor internet and VPN …
> Open tiles test

- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Removed Extra Toggle Button
-----------
I removed some layers and reduced the number of toggle buttons - this can still be changed.
I also set the HRU outlines to default to off, but allow them to be turned on - this can also be changed.
> Remove some unwanted layers

- CHANGELOG.md
- public/index.html
- src/App.vue
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Add OpenMapTiles Attribution
-----------
Added the required OpenMapTiles Attribution. I also changed the title page and the map to National 'Integrated Water Availability Assessments'.
> Add openmaptiles attribution

- CHANGELOG.md
- src/components/MapBox.vue
- src/main.js
Added a subtle subtitle, I am guessing I'll be told to make it bigger in the future, but want to initially suggest a subtle solution.  It never moves, so it will be hard to miss while exploring the map.
> Add map subtitle and subtitle info button

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapSubtitle.vue
Was asked to make the subtitle its own component for easier future tinkering.
> Create Component for Map Subtitle

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapSubtitle.vue
- src/main.js
Ended up doing the display none or display block trick because as I was just trying to code a pure JS dynamic creation of divs and styles it was becoming about triple the code as this solution was.  So just gonna say this is my solution, but will take suggestions.
> Add Subtitle information modal

- src/components/MapSubtitle.vue
I had removed this test URL in the code, but hadn't saved it so the google href made it to the code base. eye roll. So removing it here.
> Remove google href

- jenkins/Jenkinsfile.build
- package.json
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
- src/components/MapSubtitle.vue
Dependency Update 9 19 19
-----------
Just a couple of dependencies to update, and because the build time currently taking an hour to upload to S3 I also added a few minor changes to the application.
1 - turned of the 'click to tilt' for the map
2 excluded the 'nhd_order_tiles' folder from deletion during the Jenkins build process
3 ran 'npm run lint --fix' which changed the formatting to the way it likes to see it. 
> Dependency update 9 19 19

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
- src/main.js
Added the New NHD Stream Orders
-----------
Linked to David's newly created stream order tiles on 'test'
Description
-----------
This is the first step in determining which stream orders we would like on the map and how we would like to control them. 
> Add nhd stream orders

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLegend.vue
As the title states, I added this new legend text and the legend info button.  Info button has no functionality yet as that is another ticket.  The keys are still square as fontawesome doesn't really have any icons that resemble HRU's, so custom icons and VUE sounds like more work than a Friday is willing to give.  Monday will muck around with that more.
This at least gets the text up for scrutiny.
> Changed Legend Text and Added Legend Info Button

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLegend.vue
- src/main.js
Legend Modal created, exactly like the subtitle modal, but created a function for the modals functionality to eliminate the redundant code I was writing.  Still need Florida and Arizona images, and possibly a rethink of where it shows up, but content can be argued over now at least.
> Legend Modal

- CHANGELOG.md
- package.json
- src/assets/mapStyles/mapStyles.js
- src/components/MapLegend.vue
- src/components/MapSubtitle.vue
- vue.config.js
Added the vue-svg-loader npm package to the project as it made adding and editing SVGs via JS a breeze compared to what writing vanilla JS and dealing with VUE scoping.  Florida and Arizona now are in the modal and if we change the HRU color scheme, they will change dynamically with it!
Also messed around with making the modal look better on mobile.  For now it will do.
> Legend Modal finishing touches

- CHANGELOG.md
- src/components/MapBox.vue
The main part to review is the function called dynamic.  Sorry, forgot formatting the code basically makes the code unreviewable.
dynamic starts on 194.
> Layer toggle functionality

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Changed to Use Tile Server URLs
-----------
Change over to use new tile server https://maptiles-prod-website.s3-us-west-2.amazonaws.com
This serves the hill shade and the base layer tiles.
> changed to use tile server urls

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLegend.vue
- src/main.js
Legend now has toggle buttons for a better mobile experience and just if you don't want it taking up much space.
> Legend toggle

- src/assets/mapStyles/mapStyles.js
Turn of Dev URLs
-----------
Dang. 
Description
-----------
> turn of dev urls

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
List of changes:
Made HRU's opacity full 100% color
Put the HRU's behind all the layers besides the background, as you can no longer see through the HRU's
Put the water layers on top of the street layers, so when they intersect the water layer is what you see.  (Just assuming thats what we want being a water science player, can be changed easily)
Readded the states outline layer.
Recolored the counties to be the same color as the state outlines, this way the roads don't start fading in county lines.
> Solid HRU Colors

- config.sh
- jenkins/Jenkinsfile.build
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Change to use S3 tile server for base tiles
-----------
Since our S3 tile server is up and running we are switching all the tile sets that don't need regular changes to that server.
This required some changes to the build to remove code related to the old tile location.
Also added minor style change for county borders.
I also did a find and replace for double quotes to single, so there are a bunch of minor code things flagged as changes making this pull request very hard to review. :(
> changed to use s3 tile server for base files

- src/App.vue
Description
-----------
Same fix as the Delaware project for the scroll bar cutting off content issue
> scroll bar content fix

- jenkins/Jenkinsfile.build
Add Jenkins File Exclude for Date Folder
-----------
Small change to save the file for last available data date.
> add date folder exclude to jenkins file

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Added Bounds Restriction
-----------
Added code to prevent users from zooming their view out past the confines of the continental United States
> added bounds restriction

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Title
-----------
Description
-----------
Water(lakes) is now above neighboring countries in the map styles
Adjusted WBEEP Mp layers toggle to resemble the Delaware projects functionality.
> Wbeep adjustments

- src/components/MapSubtitle.vue
Description
-----------
Adjusted the top position for the absolute div to be positioned under the date
> Subtitle Modal below Date

- src/components/MapBox.vue
Adjust the Bounds
-----------
Just a tweak to get this working. 
> changed the bounds

- src/assets/mapStyles/mapStyles.js
Code to change tile cache
-----------
This is a hard coded test to see if using 'tiles': ['http://wbeep-test-website.s3-website-us-west-2.amazonaws.com/tiles/{z}/{x}/{y}.pbf?fresh=true'] instead of 'tiles': ['http://wbeep-test-website.s3-website-us-west-2.amazonaws.com/tiles/{z}/{x}/{y}.pbf] will change tile caching behavior.
> add code to stop tile cache

- CHANGELOG.md
- package-lock.json
- package.json
- src/assets/mapStyles/mapStyles.js
- src/components/FooterUSGS.vue
- src/main.js
Changed Footer Icons to Vue Components
-----------
Changed the footer icons to components
Description
-----------
This change is a result of an issue with the footer icons failing to appear correctly. It seem that this was caused by a style conflict related to recent changes in the application. I base this on the fact the the same code from this project is still working in the Delaware Basin Project.  At any rate, I used it as an opportunity to replace the existing code with Vue components. I also bypassed some of the styling that was one the old icons and replaced it with simpler code that I hope does the same thing.
> Change footer icons to vue components

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- src/assets/mapStyles/mapStyles.js
- src/components/FooterUSGS.vue
Added Grouped Streams
-----------
A simple change to let the application use David's new grouped stream orders
> Add grouped streams

- src/assets/mapStyles/mapStyles.js
Title
-----------
Description
-----------
> Adjust category name

- src/assets/mapStyles/mapStyles.js
Title
-----------
Description
-----------
> legend fix

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/MapBox.vue
- src/main.js
Added Google Analytics Plugin
-----------
Added the Analytics plugin, not really sure how Google Analytics works, so I hope this does the trick.
> added google analytics plugin

- jenkins/Jenkinsfile.build
Title
-----------
Description
-----------
> Add notifications to build pipeline

- Dockerfile
- src/App.vue
- src/components/MapBox.vue
- src/main.js
Add Google Analytics try 2
-----------
Did a bit more research and moved things around to try to get this working. Ideally, this plugin would like to be feed the page routes through the Vue-router object. Well have to try this out when the routing is ready.
> Add google analytics 2

- jenkins/Jenkinsfile.build
Trivial Change to Test Jenkins Build
-----------
I changed the 'branch specifier' from */master to origin/master to and that seemed to stop the constant building of the application. Now I want to see if the project will still build on a change.
> trivial change to see if build will trigger

- src/assets/mapStyles/mapStyles.js
Title
-----------
Description
-----------
> Use jordanpalette

- src/assets/mapStyles/mapStyles.js
Title
-----------
Description
-----------
> Use CORRECTED! jordanpalette

- src/components/MapLayers.vue
Description
-----------
Added the template tag to avoid Vue rendering errors
> template tag in the component

- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Change Button Names
-----------
Quick change to alter button names.
Also added a missing bracket, that was messing up my loop.
> fixed error due to missing brace, fixed wording on buttons

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLayers.vue
Description
-----------
Map Layers on Desktop no longer reaches to the map bottom
> Map Layers Box Adjustment

- src/components/MapLegend.vue
> Legend Modal coloring and text fix

- jenkins/Jenkinsfile.build
Title
-----------
Add post notification step to pipeline
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/175
> Re-add notifications with proper placement 

- src/App.vue
- src/components/About.vue
- src/components/MapBox.vue
- src/components/MapLayers.vue
- src/main.js
Quick Fix n Google Analytics Hooked to VueRouter
-----------
A quick fix to pass some 'props' to the 'about' component and clear up a CSS clash.
Also, added the Router object to Google Analytics plugin so that it can pick up all the routes.
> quick tweak to fix css issue and pass some props

- .env
- .env.development
- .env.production
- src/components/About.vue
- src/components/MapBox.vue
- src/main.js
Fix to Environment Variables
-----------
The addition of the routing for the About page revealed a few areas where the Vue Environment Variables could be used better. I added a '.env' file to contain the variables that should be loaded in all environments and moved the page title there. I also made a few tweaks to the Vue component data methods such that a correct 'About' page title would show on the 'about' page. 
> added general .env to simplify things

- CHANGELOG.md
Title
-----------
Update changelog 
Description
-----------
To prepare for release and to capture changes from last release
> update changelog from last release and anticipated release

- package-lock.json
- package.json
- src/components/MapLayers.vue
Dependency Update
-----------
Just a general update of project dependencies. Three of the Vue Command Line Interface (CLI) items contained breaking changes. But I ran the build locally and all seemed to work as expected. 
> Dependency update 10 21 19

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
Description
-----------
- Added Flow Detail between maplayers and stream layers.
- Added class to the individual layers titles
- Added darker gray background to titles to help differentiate titles from map options
> Stream Reach Rename and add Flow Detail

- src/assets/mapStyles/mapStyles.js
Description
-----------
Counties are now off by default and have been added to the maplayers toggle options div for users to use at their discretion 
> Counties off by default

- src/assets/mapStyles/mapStyles.js
Description
-----------
Moved the Terrain style on top of the neighboring countries, looks snazzy to me.
> Hillshade on top of neighboring countries

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLayers.vue
Description
-----------
Added functionality for the Flow Detail Options that checks to se if any of them are active when one is clicked, to allow only one option be active at any given time.  MapLayers remain untouched and can have all the options on at once.
> Layers update

- src/main.js
Make Application work on IE 
-----------
Not sure if this fix will work, but as I have no way to test it locally and the change is small, I will push it up and see if it helps. If not I will have to find another plan.
> changed router insert to js object

- src/main.js
Fix for IE didn't work, so need to revert
-----------
> revert change

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
Title
-----------
New styles for new river tiles :coming-soon:
Description
-----------
After regenerating map tiles for the rivers, we'll need to update this style.
Wait to merge until https://github.com/usgs-makerspace/wbeep-processing/pull/83 is merged and has run successfully.
> Update to map style for new river tiles

- CHANGELOG.md
- src/components/LoadingScreen.vue
Description
-----------
Console was complaining that fix.addEventListener wasn't a functions as it was applied to a class, even though it was still functioning as I expected I hate red errors in the console if they are avoidable.  So gave the div an ID and made the fixed variable find that instead of the class.  Same functionality, less errors! yay.
> Fix errors to prevent touchmove

- vue.config.js
Fix for Edge Maybe
-----------
After hours of searching, narrowed down the list of potential issues. This seems to fix the issues with the Edge browser.
Description
-----------
> added fix to get edge working

- package-lock.json
- package.json
- src/components/LoadingScreen.vue
- src/components/MapAvailableDataDate.vue
Testing a Polyfill for Fetch
-----------
I am going to try this fix on 'test' and revert it if necessary. It is a very small addition of the 'whatwg-fetch' polyfill.
> polyfill for fetch

- CHANGELOG.md
- src/components/MapBox.vue
Description
-----------
We didn't have pinch t zoom for the map, luckily this tiny one line adds that functionality.
> Pinch to Zoom

- src/components/MapBox.vue
Turn off loading screen to test ie
-----------
> turned off loading screen to test ie

- package-lock.json
- package.json
- src/components/LoadingScreen.vue
- src/components/MapAvailableDataDate.vue
- src/components/MapBox.vue
- src/main.js
Turn Off the Loading Screen only for Internet Explorer
-----------
Added a small plugin to make it easy to grab the browser used. Used that selection to turn off the loading screen for people using Internet Explorer.
> Fix for edge

- src/assets/mapStyles/mapStyles.js
Title
-----------
Try filtering out common from the HRU's #266
Description
-----------
Drop undefined and average categories
> Remove average and undefined categories

- src/assets/mapStyles/mapStyles.js
Title
-----------
Description
-----------
> Average and no data are set to background color

- build.sh
Update Tiers in Build Script
-----------
Oops, forgot to update the tiers in the build script - hey nobody is perfect
> added ifs for tiers in build script

- .env.beta
- .env.qa
- .env.test
Changed Tier Name
-----------
Tiny change to make the tier level more clear
> changed format of tier name

- src/assets/mapStyles/mapStyles.js
Title
-----------
change styles back to what they currently are on QA 
Description
-----------
NA
> Revert style change temporarily so we can cut a release for QA

- CHANGELOG.md
- src/components/InternetExplorerPage.vue
- src/components/MapBox.vue
End Support for Internet Explorer
-----------
As a team we have decided to end support for Internet Explorer (IE). This pull request creates a page the will intercept IE users and request that they return with a different browser.
> Add ie intercept

- CHANGELOG.md
- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/278
Description
-----------
drop drop shadow from legend text
> drop the drop shadow

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
- src/components/About.vue
- src/components/MapLegend.vue
…bout page
First . . .
Finally . . .
Title
-----------
open about links in new page
https://github.com/usgs-makerspace/makerspace-sandbox/issues/277
Many legend changes: adjust legend text, color swatches, drop the drop shadow.
Description
-----------
open about page links in new page
improve legend readability and wording
> About page links/Legend edits

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
the previous width was affecting the minimized legend, this does not. :tada:
Description
-----------
> Adjust css for legend width

- src/assets/mapStyles/mapStyles.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Simplify legend wording

- src/assets/mapStyles/mapStyles.js
- src/components/MapBox.vue
First . . .
Finally . . .
Fixing Error with Google Analytics and changing zoom level
-----------
In the last pull request I forgot that the old form of the Google Analytics was still needed to run the the Google Analytic events that are dynamically created. Not quite sure how the error went undetected in local testing, but hey, this should get things back on track again.
> added coded to get local version of GA variable

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Removing Change to Jenkinsfile
-----------
Well, the previous change didn't work so backtracking a bit
> removing jenkinsfile change

- CHANGELOG.md
- src/assets/mapStyles/mapStyles.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Rivers on all zoom levels

- jenkins/Jenkinsfile.build
- src/main.js
- src/router.js
- src/views/Error404.vue
First . . .
Finally . . .
Improved Code Pattern for Routes
-----------
This fixes an error with a component name and removes the routeing code from 'main.js' 
> improved code pattern for routes

- CHANGELOG.md
- src/components/MapBox.vue
- src/components/MapLegend.vue
First . . .
Finally . . .
Fix Minor Usability Issues
-----------
Fixed issue where layers menu covered zoom controls
Fixed issue where only icon in 'close box' was clickable.
> fixed usabity issues

- src/components/LegendModal.vue
- src/components/MapBox.vue
- src/components/MapLegend.vue
- src/components/SubtitleModal.vue
First . . .
Finally . . .
Description
-----------
Better looking $emit functionality
> Code Cleanup

- .env
- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/components/MapBox.vue
- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Setup Questions Page to Auto-Generate from JSON
-----------
After attempting to update the 500+ lines of code for the Questions page manually and causing numerous errors, I decided to automate. Now no code needs to be touched update the questions page, just make the changes in the JSON files, and 'poof' new page, no code errors. This also reduced the code from 500+ to less than 50 -- much easier to find and fix errors.
> minor cosmetic changes

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Collapsed Legend Arrow Hover

- package-lock.json
- package.json
First . . .
Finally . . .
Update Dependencies 12 9 19
-----------
General dependency update
> Update dependencies 12 9 19

- .env.test_tier
First . . .
Finally . . .
This is an addition to the change URLs pull and just changes the 'test' URLs
-----------
> changed the urls for test

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Add a Missing Quote
-----------
> add missing quote

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Remove the Leading Slash
-----------
> remove the leading slash

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Remove Old 'Excludes' from Jenkinsfile
-----------
The new changes seemed to work so let's let the build job delete the old tile and date folders.
> removed original jenkins excludes

- src/components/MapBox.vue
- src/components/ProvisionalStatement.vue
- src/main.js
- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Making the Provisional Statement Pretty with Toggle
-----------
Due to the formidable wave of hate directed at my previous provisional statement, I have made a slicker, cuter, and more improved version. I also removed some 'props' that were no longer in use.
> Wbeep provisional statement toggle

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> grammar changes and small rearranging of Q&As

- package-lock.json
- package.json
First . . .
Finally . . .
Dependency Update 12 12 19
-----------
Another general dependency update in preparation for release
> Update dependencies 12 12 19

- src/App.vue
- src/components/ProvisionalStatement.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Warning text has the same font stack as the rest of the app.  Was USWDS fighting our previous declaration.  Also removed /or
> Same font and text change

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> update a few small things on the Q & A page

- src/images/states/example.svg
First . . .
Finally . . .
Title
-----------
still seeing a 404 in the console even after adding the png referenced in the svg. it doesn't seem required so dropping the reference to the png from within the svg to see if we lose the 404 and nothing else. works locally but s3 is a little different.
Description
-----------
> Drop reference to PNG entirely

- package-lock.json
- package.json
First . . .
Finally . . .
Dependency Update
-----------
Nothing of any really interest, just a general dependency update.
> Dependency update 12 20 19

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
converge on a layperson term for conterminous/coterminous
Description
-----------
skipped one conterminous as it was in a paper title
> Modify language to lower 48 instead of coterminous or conterminous

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
noticed we already used 'lower forty-eight states' somewhere in the Q & A so decided to change all occurrences to match that.
Description
-----------
> consistent use of lower forty-eight states all over

- CHANGELOG.md
- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Drop the CONUS verbiage

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Do not Use this as a Decision Making App

- src/components/ProvisionalStatement.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> New text and a small text removal

- package-lock.json
- package.json
First . . .
Finally . . .
Fix Broken Build
-----------
Seems like the Vuex dependency didn't get pushed to the canonical repository. Gonna try adding it again. 
> npm install vuex

- package-lock.json
- package.json
First . . .
Finally . . .
Update More Dependencies 
-----------
Nothing real exciting. Just regular maintenance.
> Update more dependencies 3 4 20

- package-lock.json
- package.json
First . . .
Finally . . .
Dependency Update
-----------
Just a small dependency update
Note, I can't seem to get Browserstack to test local files on my machine at the moment, so I wasn't able to do cross browser testing.
> Update dependencies 3 12 20

- CHANGELOG.md
- src/App.vue
- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/components/ApplicationFeatureSelection.vue
- src/components/NotPubliclyAvailable.vue
- src/components/QuestionControl.vue
- src/router.js
- src/views/waterStorage/WaterStorage.vue
- src/views/waterStorage/WaterStorageQA.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterTemperature/WaterTemperatureQA.vue
- src/views/waterUse/WaterUse.vue
- src/views/waterUse/WaterUseQA.vue
First . . .
Finally . . .
Add Base maps for Temperature Prediction 
-----------
Adds the base maps for the as a starting point for Temperature prediction
Description
-----------
In addition to base maps this adds several 'behind the scenes' improvements.
- Hides the new features and adds warning text to new feature pages on the off chance that someone types in the exact URL of the new page (since the tab that route to those pages there is no navigation to those pages, but 'in theory' someone might enter the feature page URL and see the contents, so this prevents that from happening.
- Reworks the way the Internet Explorer Intercept …
> Wbeep 465 framework temp map

- .gitignore
- CHANGELOG.md
- package.json
- src/assets/mapStyles/waterUse/mapStyles.js
- src/components/ProvisionalStatement.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Description
-----------
I got a mapbox map loaded up and styled separately from the other 2 maps.  Also added .DS_STORE into the gitignore, thought we had it in there before, but must of been a previous project
> Intial Water Use Map Setup

- .env.beta_tier
- .env.prod_tier
- .env.qa_tier
- .env.test_tier
- CHANGELOG.md
- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Add Streams to Temperature Map
-----------
This accesses the tile Megan created.
> Add Streams to Temperature Map

- package-lock.json
- package.json
- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Development Options for Color Ramp
-----------
Added a 20 step color ramp, which is basically continuous from red to blue and development input fields to allow for testing.
> Wbeep 467 temperature color ramp

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Add Development Sample Color ramps and Light Dark background
> added light dark selection and default ramps

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
- [x Firefox
Finally . . .
Added Sample Zoom to Region Feature
-----------
This is intended to be an example of what can be done, not a final product. That said, I added three buttons that allow the user to jump to a region of interest. In each 'region of interest' I have added highlights to stream 'reaches'. The highlights are determined by temperature, with the 'salmon habitat' highlighting areas that 5-10 C, trout 5-10 C (but different color), and mussels 15-20 C.
> Wbeep 471 button zoom to region

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Title
-----------
Description
-----------
> Update jenkinsfile to use makerspace jenkins node

- CHANGELOG.md
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Description
-----------
Moved the water use data to the mapprodtiles s3 bucket.  Have it working successfully locally, hopefully continues as it goes upward.
> Water Use Data on S3

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Lets make sure this is what you meant
> Async Loading for the data

- jenkins/Jenkinsfile.build
the existing team:makerspace node is a very large node to support geospatial data processing and is not likely needed at this time for this project
First . . .
Finally . . .
Title
-----------
Description
-----------
> Use smaller makerspace team jenkins node

- CHANGELOG.md
- package-lock.json
- src/App.vue
- src/components/ApplicationFeatureSelection.vue
- src/views/waterStorage/WaterStorage.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Refine Feature Navigation
-----------
This implements the changes indicated at the Crit. 
Description
-----------
The break point for mobile/desktop is 950
The text also changes at the above point, and drops the  'water' prefix
Highlight is controlled by the route name since the component controlling the navigation and title is separate from the 'map' component and needs the route to know which 'map' (feature) is active.
> Wbeep 482 refine navigation

- src/components/waterUse/RadialChart.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Radial Chart Component

- package-lock.json
- package.json
- src/components/ApplicationFeatureSelection.vue
- src/components/MapSubtitle.vue
- src/components/SubtitleModal.vue
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> added placeholder text for temperature

- src/components/ApplicationFeatureSelection.vue
First . . .
Finally . . .
Fix - only text on router links were clickable
-----------
This makes it so the the area around the text is clickable.
> Wbeep fix make link area active not just text

- .env.beta_tier
- .env.prod_tier
- .env.qa_tier
- .env.test_tier
- CHANGELOG.md
- src/components/LoadingScreenInternal.vue
- src/views/waterStorage/WaterStorage.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
first attempt to modify the loading screen
Description
-----------
issue: https://github.com/usgs-makerspace/makerspace-sandbox/issues/486#issuecomment-656667582
created a copy of the existing loading screen and renamed internal in case we still want to (somehow? i wasn't sure) use the original on first load of the website. 
I modified the copy and shifted the loading splash down below the header and navigation links. on load, i disable the scrollbar as well since that was kind of funky, and then remove the class that disables the scroll bar after loading. not sure if this is the ideal …
> Loading screen change

- .env.beta_tier
- .env.prod_tier
- .env.qa_tier
- .env.test_tier
- CHANGELOG.md
First . . .
Finally . . .
Title
-----------
change location of waterStorage tiles https://github.com/usgs-makerspace/makerspace-sandbox/issues/498
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/498
> change location of water storage tiles

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/585
Description
-----------
add outage notice 
> add outage notice

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
remove outage from master branch, will repush to alternate branch
Description
-----------
remove outage from master branch, will repush to alternate branch
> remove outage notice from master branch

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Add interpolated ramp streams layer using blue to red, add a toggle for layer
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/590
> add interpolated ramp and toggles

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> forgot to remove local tile ref

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
tweaks to styles
Description
-----------
turn off most of the waterway background tiles because they conflict with our water temperature data
modify thickness of zoomed in water temp layer so that it's not as thick per feedback 
> style tweaks

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
was still seeing black features in the stream temp layer so adding another filter to handle those
Description
-----------
add a filter to remove any features with non numeric values from display
> filter out NaN pt II

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Only allow zooms to 6 
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/603
> Limit overall zoom level for map

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
minor line width change
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/603#issuecomment-671628579
> make highest zoom level not so wide

- .env.qa_tier
- CHANGELOG.md
First . . .
Finally . . .
Title
-----------
prepare for QA release of work from test
Description
-----------
added to and modified changelog for release
modified env file to display tabs to switch between water sections
> updates for qa release

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> turn old streams off and new streams on by default

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> when toggling habitat areas off, leave interp streams on

- jenkins/Jenkinsfile.build
First . . .
Finally . . .
Change Build Email List
> change email list

- .env.beta_tier
- .env.prod_tier
- .env.qa_tier
- .env.test_tier
- src/components/MapAvailableDataDate.vue
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
the water temperature tiles will have a different date than our water storage tiles, so show that date instead
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/613
> show tile date on water temp view

- package-lock.json
- src/App.vue
- src/views/waterStorage/WaterStorage.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Created a basic HTML wireframe for the new Water Use page.
Some CSS was using CSS connected to all three pages so adjustments had to be made on them to make sure the old layouts still worked.
Basically @lindsayplatt could you see if everything still looks like you'd expect?  I checked on three browsers and several screen size and didn't notice anything, but two eyes are always better
> New HTML layout for Water Use

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
add layer list toggle to water temp map
https://github.com/usgs-makerspace/makerspace-sandbox/issues/611
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/611
bring over code and styles needed in order for this function to work.
> enable layer toggle list on water temp map

- src/components/MapAvailableDataDate.vue
- src/components/MapSubtitle.vue
- src/components/SubtitleModal.vue
- src/views/waterStorage/WaterStorage.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> About map component

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Created a div to act as the Question mark.  The current Question component is a specifically made custom control for a mapbox map, which this page is not.  It acts and looks just like those question marks in my opinion, so should be good to go.
> Add Question mark to water use page

- src/components/MapLegend.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added new legend function that creates a legend based on what page you are on, so I wouldn't have to recreate the legend from scratch.  It dynamically adds the info button as well based on what page you are on.  Vue got the stuff.
> Water temp legend

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
Modify style for roads layer
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/628
> Make roads brown again

- src/views/waterUse/WaterUse.vue
- vue.config.js
First . . .
Finally . . .
Title
-----------
Description
-----------
Lindsay did some scaling magic to make FF happy.  I don't know why it was so picky, but we witnessed it working together.
> FireFox Bug Fix

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
Adds:
```
.wu-bars-axis {
font-size: 20px;
}
path.wu-bars-axis {
stroke: black;
stroke-width: 5;
}
.wu-bars-hover {
opacity: 0.2;
}
```
> Add a y axis

- src/components/DynamicSVG.vue
- src/components/LoadingScreenInternal.vue
- src/store/store.js
- src/views/waterUse/WaterUse.vue
- vue.config.js
First . . .
Finally . . .
Title
-----------
Description
-----------
Trying to have the loading screen stay up until the map svgs are done loading.  Locally the maps load like lightning so I can't tell if what I did worked, but it loads super slow on test, so guess I have inefficiently test it out there?
> Water use parameter colors & loading screen timing for water use

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
- wu_pipeline/6_visualize/src/build_svg_map.R
- wu_pipeline/6_visualize/src/svg_utils.R
- wu_pipeline/6_visualize_wu.yml
Adjusted so that we can see the axis and text.
> custom viewbox for bar charts

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- src/components/LoadingScreenInternal.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Using a fancy Vuex tactic Aaron taught me today to watch to see if the map svg is done rendering and then tell the loading screen to go away.  Also new classes added to the dots creates smooth color changes between water use parameters switches.  
> Attempt #2 to make sure map is loaded

- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/components/DynamicSVG.vue
- src/store/store.js
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Getting Public Supply in the mix so we don't have a disabled button in the app.  
> Add Public Supply

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
Update about this map text for water use and water temperature
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/615
https://github.com/usgs-makerspace/makerspace-sandbox/issues/619
> Adjust about this map text

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/assets/references/references.js
- src/components/References.vue
First . . .
Finally . . .
Title
-----------
Add to the questionsAndAnswers page sections for water temperature and water use
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/622
https://github.com/usgs-makerspace/makerspace-sandbox/issues/620
> add new sections for water use and water temp to q and a page

- .env.beta_tier
First . . .
Finally . . .
Title
-----------
change flag to show the tabs on beta so we can look at that on mobile
Description
-----------
no ticket
> adding tabs to beta tier so we can more easily test on mobile

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/assets/references/references.js
- src/components/QuestionControl.vue
- src/components/QuestionsAnswersAccordion.vue
- src/components/SubtitleModal.vue
- src/router.js
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added scroll to to the router, so it responds to the # tags we add to the route links.  Now when you click each individual question mark it takes you to that section in the QA.  Also the back buttons now take you back to that specific map.
> Router business

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Think there a few CSS changes in here, nothing officially picked was just messing around, but the changeSeason should not fire unless the div with the specific class is clicked and can render and image.
> yAxis click bug fix

- src/components/ApplicationFeatureSelection.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Simple text change and Font matching up between our header and app font.  
> Small changes

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
I was missing one function call and a data element.
> Stop double tapping x

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Barchart now changes the wubar chunk color and when hovering over the unactive seasons shows a more transparent water use parameter color which goes full opacity when selected as the activeSeason.  The season still persists through water use parameter changes and the hover color is dynamically changed too.
> New Color Functionality

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Trying to get a basic view fit into short and wide monitors, hopefully hit a somewhat sweet spot for now.
> Some CSS for Windows comps

- src/components/SubtitleModal.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Water Use Parameter buttons get the pointer cursor.  Adjusted the About map text for water use and made it more opec? opace? Whatever less transparent. 
> Pointer for buttons and about this map edits

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> use to uses

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Words were requested to be added
> Rewording for water use about this map

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added fahrenheit to legend 
> Imperial Temp

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added instruction numbers.  Went with the blue of the header and footer.  Felt like that made it flow and separate the colors from the map colors.  On smaller phones the text wraps but I don't think that is a game changer personally.
> Add Instruction Numbers

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
SVG Barchart now has seasons
> Season labels for bar chart

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Noticed the hover effect worked on the collapsed legend but not the expanded legend.  So adjusted the CSS to work for both.
> Legend minimize bug

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
In my quest to figure out how to design for all possible screens is still on going, I have the thought if you have a taller and wide screen you deserve a large map.
> Wide and tall screens get a larger map

- src/components/DynamicSVG.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Just adding a prefetch for webpack.
> prefetch the SVG webpack

- src/components/DynamicBarChart.vue
- src/components/DynamicSVG.vue
- src/components/MapLegend.vue
- src/components/SubtitleModal.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Lint fixes haven't been run in awhile so just doing that now.
> lint fixes

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Forgot to make the map gray
> Make map gray

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Still just trying to tweak the loading screen times
> Loading Screen Fiddling

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Instructions Text Change

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Was requested to use the word per instead of /
> Speel out per for WU legend

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
Add month abbreviations to x axis
unstyled view:
> Season label additions

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Messing with colors for the month labels to not have them competing with the season labels as much
> Deemphasize month labels

- src/components/SubtitleModal.vue
First . . .
Finally . . .
Title
-----------
Jen mentioned in her draft email announcement that this said 110,000 which is wrong/probably a copy/pasta. fixing.
Description
-----------
text says 110,000 but it's 58,000 ish
> fix number of stream segments/reaches

- src/components/QuestionsAnswersAccordion.vue
- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added Section Headers and modified button texts.  Both add up to a much more clear blockage of content.
> Update buttons and section headers

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Just a simple hover effect to let people know they can click the irrigation winters.  
> Simple Hover Effect

- wu_pipeline/6_visualize/src/seasonal_map_tasks.R
Doesn't directly change anything in the viz. Reported results to Marty [here](https://github.com/usgs-makerspace/makerspace-sandbox/issues/650#issuecomment-704394174) that can be used.
To see the values, run this:
```
library(scipiper)
setwd("wu_pipeline")
te_legend <- scmake("legend_vals_te_promise", "6_visualize_seasonal_map_tasks_te.yml")
ir_legend <- scmake("legend_vals_ir_promise", "6_visualize_seasonal_map_tasks_ir.yml")
ps_legend <- scmake("legend_vals_ps_promise", "6_visualize_seasonal_map_tasks_ps.yml")
```
> add 2nd final step to get values to use in map legend

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
I am probably not coding this very well, but tried to keep my code from being redundant as much as I could.  Basically checking if its a winter path and running separate code from when its any other season.  Anyway, I, a graphic designer, got this to work, so there world! Take that.
> Double Winter Highlight

- src/components/WorkInProgressWarning.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Was requested we add the work in progress banner for temp and use.  Its nice you can just swap in components where you need them.  
> Work in Progress Component

- src/assets/wuMapSVGs/svg_map_ir_fall.svg
- src/assets/wuMapSVGs/svg_map_ir_spring.svg
- src/assets/wuMapSVGs/svg_map_ir_summer.svg
- src/assets/wuMapSVGs/svg_map_ir_winter.svg
- src/assets/wuMapSVGs/svg_map_ps_fall.svg
- src/assets/wuMapSVGs/svg_map_ps_spring.svg
- src/assets/wuMapSVGs/svg_map_ps_summer.svg
- src/assets/wuMapSVGs/svg_map_ps_winter.svg
- src/assets/wuMapSVGs/svg_map_te_fall.svg
- src/assets/wuMapSVGs/svg_map_te_spring.svg
- src/assets/wuMapSVGs/svg_map_te_summer.svg
- src/assets/wuMapSVGs/svg_map_te_winter.svg
- wu_pipeline/6_visualize/src/build_svg_map.R
Added `smallDot` and `legendTitle` classes as requested :)
> add a few extra classes

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
Some nudges to stop labels and the y axis max from being covered up
> increase spacing at top and bottom of bar chart

- src/components/MapLegend.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Cleaned up the map legend component as we aren't using that solution anymore.  Styled Lindsays new legend group and think we are good to go currently with what I decided looked good.  @mhines-usgs let me know how it looks on your comp.
Also added space between the bar chart and the feedback text
> Fancy new water use legend

- src/assets/wuMapSVGs/svg_map_ir_fall.svg
- src/assets/wuMapSVGs/svg_map_ir_spring.svg
- src/assets/wuMapSVGs/svg_map_ir_summer.svg
- src/assets/wuMapSVGs/svg_map_ir_winter.svg
- src/assets/wuMapSVGs/svg_map_ps_fall.svg
- src/assets/wuMapSVGs/svg_map_ps_spring.svg
- src/assets/wuMapSVGs/svg_map_ps_summer.svg
- src/assets/wuMapSVGs/svg_map_ps_winter.svg
- src/assets/wuMapSVGs/svg_map_te_fall.svg
- src/assets/wuMapSVGs/svg_map_te_spring.svg
- src/assets/wuMapSVGs/svg_map_te_summer.svg
- src/assets/wuMapSVGs/svg_map_te_winter.svg
- wu_pipeline/6_visualize/src/build_svg_map.R
This ones for you @mwernimont 😉
> incorporate Marty's manual nudge into the code

- src/components/WorkInProgressWarning.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Jen requested a language change for the banner.
> Text change for warning banner

- src/assets/wuMapSVGs/svg_map_ir_fall.svg
- src/assets/wuMapSVGs/svg_map_ir_spring.svg
- src/assets/wuMapSVGs/svg_map_ir_summer.svg
- src/assets/wuMapSVGs/svg_map_ir_winter.svg
- src/assets/wuMapSVGs/svg_map_ps_fall.svg
- src/assets/wuMapSVGs/svg_map_ps_spring.svg
- src/assets/wuMapSVGs/svg_map_ps_summer.svg
- src/assets/wuMapSVGs/svg_map_ps_winter.svg
- src/assets/wuMapSVGs/svg_map_te_fall.svg
- src/assets/wuMapSVGs/svg_map_te_spring.svg
- src/assets/wuMapSVGs/svg_map_te_summer.svg
- src/assets/wuMapSVGs/svg_map_te_winter.svg
- wu_pipeline/6_visualize/src/build_svg_map.R
Tiny dot was forgotten + need a bit more space due to font differences.
> a little extra spacing + class on tiny dot text

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
put the terrain on top of the countries layer
Description
-----------
put the terrain on top of the countries layer
> adjust terrain layer ordering

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Just right aligning the numbers on the legend.  @mhines-usgs would like for you to check for consistency across machine sthough.
> Right Aligned Legend Numbers

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/assets/references/references.js
First . . .
Finally . . .
Title
-----------
Description
-----------
Just updating the text files.
> QA Updates

- src/assets/references/references.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> New Reference Link

- src/components/QuestionsAnswersAccordion.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Put the ID I am using in the code to scrollTo in vue to the section headers.  This way when users select a question mark from use or temp those headers are visible when the QA page loads.
> Have header shown when scrolling directly to section

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
Might need to decrease text size slightly, but I think it will fit.
> add "National" to y axis label

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Simple CSS to see irigation

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Water Use and Temp QA Updates 2nd time

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Water Use QA redundant within

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> Yellow Highlight QA update

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/690
Description
-----------
per reviewer feedback, also link references within the text space on the ? page.
> add inline references throughout the ? page

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
changed an old mailto link that wasn't working for me at least on the current site, adding more inline references I missed on the first scan
Description
-----------
testing my recent changes I came upon this link that wasn't working correctly, I am seeing a 404 on click on the current test page. i don't know that we'll need to change these email addresses much so I'm not too worried about making it work with the Vue variable. 
more refs added
> modify old inline reference, add more inline refs

- src/components/ApplicationFeatureSelection.vue
- src/components/WorkInProgressWarning.vue
- src/router.js
- src/views/About.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Created the About page route, added the about menu option, and finally created the about page sans content
> About page

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Text has been modified to "Spring season is the default view"
> WBEEP #678: water use - change wording on step 1

- src/assets/wuBarSVGs/svg_bars_ir.svg
- src/assets/wuBarSVGs/svg_bars_ps.svg
- src/assets/wuBarSVGs/svg_bars_te.svg
- wu_pipeline/6_visualize/src/build_svg_bars.R
@mwernimont use class `wu-season-dividers` to style the paths a la https://github.com/usgs-makerspace/makerspace-sandbox/issues/672
> add lines on chart to divide seasons

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Initial color of the dividers is thermo, then the function takes control as the user switches between parameters
> Season Dividers

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/681
Description
-----------
drop the roads layer per reviewer feedback. also adjust the size of the map layer list container which contains extra space after removing that layer.
> drop roads, reduce container size for water temp

- src/components/LegendModal.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/688
Description
-----------
Reviewer suggested dropping the 'yes' since we don't really answer the yes part of the question. Here is my suggestion to update the text:
> update legend info text

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/687
Description
-----------
feedback from reviewer
> updating text for water temperature/stream temperature

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Middle temp label as requested. 
> Temp Middle Legend Label

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
adjust order after noticing we lost central and south america, for example.
Description
-----------
related to work done on this task: https://github.com/usgs-makerspace/makerspace-sandbox/issues/680
> re-order layers so that we don't lose other land masses

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> remove unused code, toggle terrain off by default

- src/assets/questionsAndAnswers/questionsAndAnswers.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/679
Description
-----------
Updating language based on feedback from reviewer
> water use wording changes for clarity

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/components/MapSubtitle.vue
- src/components/QuestionsAnswersAccordion.vue
- src/components/SubtitleModal.vue
- src/views/About.vue
- src/views/QuestionsAndAnswers.vue
- src/views/waterTemperature/WaterTemperatureQA.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Updated QA page text and subtitle updates
> Text Update for QA and Storage and Use subtitles

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/assets/references/references.js
First . . .
Finally . . .
Title
-----------
Description
-----------
> add links back

- src/components/QuestionControl.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Fix my function

- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
QATab class was messing with the legend tabs, now its not
> legend css bug

- src/components/SubtitleModal.vue
- src/views/About.vue
- src/views/QuestionsAndAnswers.vue
- src/views/waterStorage/WaterStorageQA.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Hitting the learn more on the appropriate maps sends you to the correct QA tab now
> lint fixes and learn more goes to the correct tabs

- src/assets/mapStyles/waterTemperature/mapStyles.js
make the stations slightly more visible while we decide what to do with them...
First . . .
Finally . . .
Title
-----------
add color back to station locations while we test
Description
-----------
> change opacity of stations

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
pushed out to beta and it complains because of mixed content and refuses to load the non https version of the json file - fixing
Description
-----------
> Use secure endpoint for station data

- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Fix footer issue

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Use updated qw station layer, update field name

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/components/SubtitleModal.vue
- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Upped max zoom by 2, so 5.99 to 8.  Added the sites to the layers menu.  Changed the text in the map blurb.
> Water Temp Tweaks

- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
It help when you actually push code to a PR
> Code for the left align

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/692
Description
-----------
symbol smaller, and green
update legend to follow
> adjusting symbol for stations

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Whilst hovering, your cursor shall turn into a pointer if thou are overth a dot.  
> Water temp map

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/components/MapLegend.vue
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/692
Description
-----------
> use small black dot for stations

- .env
- src/components/ApplicationFeatureSelection.vue
- src/views/waterStorage/WaterStorage.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Changed the apps title by request, kept the build description as it does help me see what version I am on.
> App Title Change

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/692
Description
-----------
add changing circle radius so that as we zoom in, we get a bigger dot representing the station.
> make it so dot grows as we zoom in

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
pop ups were too b ig on mobile, so we are taking it down a notch
> Smaller popups on mobile

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/667
Description
-----------
> add major river names to water temp map

- src/views/About.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Very small tweaks
> Abotu page text edits

- src/components/MapSubtitle.vue
- src/views/About.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Map subtitles for both use and temperature now contain the text "Estimated"
> Text updates

- .env
First . . .
Finally . . .
Title
-----------
Description
-----------
> Readd concept map

- src/assets/mapStyles/waterTemperature/mapStyles.js
First . . .
Finally . . .
Title
-----------
at this point we aren't happy with this implementation, and will look for other ideas down the road
https://github.com/usgs-makerspace/makerspace-sandbox/issues/667
Description
-----------
> Drop river labels

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Added a few other media queries to hopefully fit screens a little better.  It fits my laptop window pretty well, but @mhines-usgs mind testing on yours?
> popup adjustments

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> Windows Screen

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Attempt to make the graphs a little less fuzzy on windows.
> Fuzzy begone?

- src/views/waterTemperature/WaterTemperature.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
> offset for map pan

- src/assets/questionsAndAnswers/questionsAndAnswers.js
- src/assets/references/references.js
First . . .
Finally . . .
Title
-----------
move new q about concept map from water use to water storage
add sentence to end of 'whats a concept map' q on water temp and water storage
Description
-----------
? page updates
> updates from Jen

- .env.prod_tier
- src/views/About.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
last changes 🤞 for prod release.
Description
-----------
didn't realize the in progress warning wasn't configurable via a variable so removing that component from each page.
updated prod .env file to make sure the tabs display
> add tabs, drop in progress warning

- src/views/About.vue
- src/views/waterTemperature/WaterTemperature.vue
- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
missed a few spots.
> Remove more warning component code

- src/views/waterStorage/WaterStorage.vue
First . . .
Finally . . .
Title
-----------
remove additional water storage banner 
Description
-----------
remove additional water storage banner 
🔪 👁️ 
> so many banner and headers oh my

- src/views/waterUse/WaterUse.vue
First . . .
Finally . . .
Title
-----------
Description
-----------
Fixing an issue where the map is overly large and the bar chart is overly small.
> Initial test

- .env.test_tier
- src/components/ApplicationFeatureSelection.vue
- src/views/About.vue
- src/views/QuestionsAndAnswers.vue
First . . .
Finally . . .
Title
-----------
keep only the water storage components
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/698
comments out other tabs from the router/nav bar area rather than disables the tabs entirely so we can keep the about page
> discard temp and use for now

- src/views/About.vue
First . . .
Finally . . .
Title
-----------
Remove space before period
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/698#issuecomment-776939795
> remove extraneous space

- src/assets/mapStyles/waterTemperature/mapStyles.js
- src/components/MapLegend.vue
- src/views/About.vue
First . . .
Finally . . .
Title
-----------
Using same general color scheme, bin data into 4-5 bins
Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/696#issuecomment-776744149
> 6 degree bins using mapbox step expression

- package.json
The dependabot version had a conflict I wasn't sure how to resolve, and since the dependabot service changed so it will no longer resolve its own conflicts, just re-did the PR here
~~~
First . . .
Finally . . .
Title
-----------
Description
-----------
> Fontawesome icons
